---
- name: add port in firewalld
    #by default when you install redhat it get installed with firewalld a inbuilt firewall in your redhat based system
  firewalld:
    service: http
    permanent: true
    state: enabled
  when: ansible_distribution == "RedHat"
  notify: Reload Firewalld
