---
- name: create a directory /etc/nginx/sites-available
  file:
    path: /etc/nginx/sites-available
    state: directory
- name: create a directory /etc/nginx/sites-enabled
  file:
    path: /etc/nginx/sites-enabled
    state: directory
- name: copy the default nginx configuration
  copy:
    src: files/nginx-default.conf
    dest: /etc/nginx/sites-available/default
- name: create a symbolic link /etc/nginx/sites-available/default to /etc/nginx/sites-enablehd/default
  file:
    src: /etc/nginx/sites-available/default
    dest: /etc/nginx/sites-enabled/default
    state: link
