---
- name: create a tomcat directory
  file:
        path: /usr/share/tomcat
        state: directory
        owner: tomcat
        group: tomcat
- name: Download tomcat
  get_url:
        url: "{{tomcat_download_url}}"
        dest: "{{tomcat_download_location}}"

    #extract the tomcat archive
- name: extract tomcat
  unarchive:
        src: "{{tomcat_download_location}}"
        dest: /usr/share/tomcat
        owner: tomcat
        group: tomcat
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /usr/share/tomcat/bin
- name: copy tomcat service
  template:
        src: templates/tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
  when: ansible_service_mgr == 'systemd'
- name: start and enable tomcat_
  service:
        daemon_reload: yes
        name: tomcat
        state: started
        enabled: yes
  when: ansible_service_mgr == 'systemd'
