---
- name: add group tomcat
  group:
        name: tomcat
        state: present 
- name: add user tomcat 
  user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat createhome=no
